In [2]:
import numpy as np
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1], dtype=int64)

In [3]:
np.bincount([0, 0, 0, 1, 1, 1])

array([3, 3], dtype=int64)

In [4]:
np.bincount([0, 0, 0, 1, 1, 1, 23])

array([3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1], dtype=int64)

In [5]:
np.bincount([0, 0, 0, 1, 1, 1, 5])

array([3, 3, 0, 0, 0, 1], dtype=int64)

In [6]:
np.bincount([0, 0, 0, 1, 1, 1, 5], minlength=3)

array([3, 3, 0, 0, 0, 1], dtype=int64)

In [7]:
np.bincount([0, 0, 0, 1, 1, 1, 5], minlength=1)

array([3, 3, 0, 0, 0, 1], dtype=int64)